info:
  app:
    description: Test task Blog application with base CRUD operations
    name: blog-app

spring:
  application:
    name: blog-app
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:h2:file:./data/${DATASOURCE_DB_NAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true

server:
  port: 9000

blogapp:
  api:
    basePath: /blog-app-api
  swagger-enabled: true
